[[navbar]]
name = "COLab"
url = "https://colabnews.co/"
weight = 1

[navbar.params]
image = "img/logos/colab-square-all-white-trans.png"

[[navbar]]
name = "Contact Us"
url = "mailto:amplifycolorado@colabnews.co"
weight = 2

[[mobile]]
name = "Home"
url = "/"
weight = 1

[[mobile]]
name = "COLab"
url = "https://colabnews.co/"
weight = 2

[[mobile]]
name = "Add your info"
url = "http://bit.ly/AmplifyColorado"
weight = 3
post = "_blank"

[[mobile]]
name = "Community Narratives"
url = "https://colabnews.co/amplify-colorado-community-narratives/"
weight = 4

[[mobile]]
name = "Contact Us"
url = "mailto:amplifycolorado@colabnews.co"
weight = 5

[[mobile]]
name = "Donate"
url = "https://colabnews.co/donate/"
weight = 6

[[footer]]
name = "Home"
url = "https://colabnews.co/"
weight = 1

[[footer]]
name = "About Us"
url = "https://colabnews.co/mission-and-vision/"
weight = 2

[[footer]]
name = "Contact"
url = "mailto:amplifycolorado@colabnews.co"
weight = 3

[[footer]]
name = "Donate"
url = "https://colabnews.co/donate/"
weight = 4

[[follow]]
name = "FAQs"
url = "https://colabnews.co/amplify-colorado/"
weight = 1

[[follow]]
name = "Add your info"
url = "http://bit.ly/AmplifyColorado"
weight = 2
post = "_blank"

[[follow]]
name = "Community Narratives"
url = "https://colabnews.co/amplify-colorado-community-narratives/"
weight = 3
